### ISSUE TITLE
Typo in Find Nearby Planet

### ISSUE THREAD

**Issue by samihibrahim** [SpaceTradersAPI/issues-and-suggestions#88] opened 2021-03-14 18:05 UTC
A minor typo exists in the command to find nearby planets=> there is an extra equals sign.
*Currently* it is set to
`https GET api.spacetraders.io/game/systems/OE/locations token==$token \
    type==PLANET`
which results in 500 server error.

*Correct* form is:
`https GET api.spacetraders.io/game/systems/OE/locations token==$token \
    type=PLANET`

**Comment by jadlers** [comment] 2021-03-15 19:20
Good catch! Thanks for reporting :raised_hands:

**Comment by j-spacetrader-api** [comment] 2021-03-16 15:25
ah this is actually not a bug, type==PLANET is a query parameter as you are filtering the results. Payload for POST requests will be in the body, and GET endpoints take query params for filtering. Let me know if this isn't working as intended! I'll close but please re-open if there is another issue.

**Closed by j-spacetrader-api** 2021-03-16 15:25 UTC
Labels: Bug, Low

**Comment by jadlers** [comment] 2021-03-16 17:25
You're totally right @j-spacetrader-api, I was to quick on that response.
