### ISSUE TITLE
Verify rate limiting headers

### ISSUE THREAD

**Issue by artokun** [SpaceTradersAPI/issues-and-suggestions#72] opened 2021-03-09 19:47 UTC
From discord:

How does the `x-ratelimit-remaining` header work? My thought was that it would be [0, `x-ratelimit-limit`) and if you made more requests after it got to `0` within the time window that you would get 429. However I've never seen this value above `1` and don't get a 429 even after making a few more requests past `0`.

**Comment by nhowell** [comment] 2021-03-09 20:18
Possibly a duplicate of #52

**Comment by jadlers** [comment] 2021-03-09 21:40
Closing since it it indeed a duplicate of the issue mentioned in the previous comment.

**Closed by jadlers** 2021-03-09 21:40 UTC
Labels: Duplicate
